# Generated by Django 5.2.8 on 2025-11-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('user', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=100)),
                ('subscription', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
    ]
